name: world_time_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/salon.png
    - assets/location1.jpg
    - assets/location2.jpg
    - assets/location3.jpg
    - assets/location4.jpg
    - assets/location5.jpg
    - assets/location6.jpg
    - assets/google.png
    - assets/fb.png
    - assets/apple.png
    - assets/eeva_spa_logo.png